BEGIN TRANSACTION;
DROP TABLE IF EXISTS `umidita`;
CREATE TABLE IF NOT EXISTS `umidita` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`umidita`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `temperature`;
CREATE TABLE IF NOT EXISTS `temperature` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`temp`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `pressioni`;
CREATE TABLE IF NOT EXISTS `pressioni` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`pressione`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `position`;
CREATE TABLE IF NOT EXISTS `position` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`lon`	REAL NOT NULL,
	`lat`	REAL NOT NULL,
	`alt`	REAL NOT NULL,
	`missionID`	TEXT NOT NULL,
	`time`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `orientation`;
CREATE TABLE IF NOT EXISTS `orientation` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`missionID`	TEXT NOT NULL,
	`x`	REAL NOT NULL,
	`y`	REAL NOT NULL,
	`z`	REAL NOT NULL,
	`w`	REAL NOT NULL,
	`scale`	REAL NOT NULL,
	`time`	INTEGER NOT NULL
);
DROP TABLE IF EXISTS `missioni`;
CREATE TABLE IF NOT EXISTS `missioni` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`missionID`	TEXT NOT NULL UNIQUE,
	`time`	INTEGER NOT NULL
);
COMMIT;
